$(window).load(function(){$('.grid').find('img').each(function(){var imgClass=(this.width/this.height>1)?'wide':'tall';$(this).addClass(imgClass);})});$(window).on('scroll',function(){var y_scroll_pos=window.pageYOffset;var scroll_pos_test=450;if(y_scroll_pos>scroll_pos_test){$('.share').fadeIn();$('header').addClass('on');}else{$('.share').fadeOut();$('header').removeClass('on');}});$(document).ready(function(){$('.menu').click(function(e){$('.popup-menu').animate({'right':0});e.preventDefault();});$('.close').click(function(e){$('.popup-menu').animate({'right':-370});e.preventDefault();});function checkUrl(test_url){var testLoc=document.createElement('a');testLoc.href=test_url.toLowerCase();url=testLoc.hostname;var what;if(url.indexOf('youtube.com')!==-1){what='youtube';}else if(url.indexOf('vimeo.com')!==-1){what='vimeo';}else if(url.indexOf('soundcloud.com')!==-1){what='soundcloud';}else if(url.indexOf('audiomack.com')!==-1){what='audiomack';}else if(url.indexOf('vimeo.com')!==-1){what='vimeo';}else{what=url;}
return what;}
$('.content iframe').each(function(){url=$(this).attr('src');network=checkUrl(url);$(this).wrap('<div class="iframeWrap '+network+'" data-src="'+$(this).attr('src')+'"><a href="#" class="load"><span>'+network+' <i>CLICK TO LOAD</i></span></a></div>');$(this).remove();});$('.iframeWrap .load').click(function(e){url=$(this).parent().attr('data-src');$(this).parent().html('<iframe frameborder="0" allowfullscreen src="'+url+'"></iframe>');$(this).fadeOut();e.preventDefault();});if(!$('.is_mobile').is(":hidden")){$('.share .tw').click(function(){var now=new Date().valueOf();appurl=$(this).attr('data-app');weburl=$(this).attr('href');window.location=appurl;!window.document.webkitHidden&&setTimeout(function(){setTimeout(function(){if(new Date().valueOf()- now<100){window.location=weburl;}},10);},50);return false;});}else{$('.share a').click(function(){window.open($(this).attr("href"),"popupWindow","width=600,height=300,scrollbars=yes");return false;});}});$(function(){var slide=$('.slider li');slide.each(function(){$('.pager').append('<a href="#"></a> ');});var pager=$('.pager a');var progress=$('.prg');var lastElem=pager.length-1;var target;pager.first().addClass('active');slide.hide().first().show();timer();function effect(target){eff=slide.parents('ul').attr('data-effect');switch(eff){case'fade':slide.fadeOut(600).eq(target).fadeIn(1200);break;case'slide':i=$('.pager .active').index();t=$('.pager a').length;h=slide.find('img').height();slide.fadeIn();if(i<(t-1)){i++;}else{i=0;}
slide.parents('ul').animate({'top':-(h*i)},500,function(){args=$(this).attr('data-attr').split(",");$.each(args,function(i){$('.'+args[i]).html(slide.eq(target).attr('data-'+args[i]));});});break;default:slide.fadeOut(600).eq(target).fadeIn(1200);}
pager.removeClass('active').eq(target).addClass('active');}
pager.click(function(e){if(!$(this).hasClass('active')){target=$(this).index();effect(target);reset();e.preventDefault();}});function next(){target=$('.pager .active').index();target===lastElem?target=0:target=target+1;reset();effect(target);}
$('.next').click(function(){next();});function reset(){progress.stop();progress.css({width:'0%'});progress.animate({width:'100%',opacity:'1.0'},{duration:15000,complete:function(){progress.css({width:'0%'});next();timer();}});}
function timer(){var attr=slide.parent().data('time');if(typeof attr!==typeof undefined&&attr!==false){defaultTime=attr;}else{defaultTime=15000;}
if(slide.length>1){if($(progress).length){progress.animate({width:'100%'},{duration:15000,complete:function(){progress.css({width:'0%'});next();timer();}});}else{setTimeout(function(){next();timer();},defaultTime);}}else{pager.remove('a');}}});
